---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homebridge.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfspv 
  resources:
    requests:
      storage: 5Gi
