apiVersion: v1
kind: Service
metadata:
  name: {{ include "homebridge.fullname" . }}
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.web.port }}
      protocol: TCP
      targetPort: {{ .Values.service.web.targetPort }}
    - name: webhook
      port: {{ .Values.service.webhook.port }}
      protocol: TCP
      targetPort: {{ .Values.service.webhook.targetPort }}
  selector:
    {{- include "homebridge.selectorLabels" . | nindent 4 }}
